### ISSUE TITLE
Add a "show materials needed" option

### ISSUE THREAD

**Issue by ThatDFlo** [rebane2001/mapartcraft#104]
Please for the love of god add an option to show all of the materials needed for the map art. Using this program is impossible for someone who wants to create map art in survival. It would take extremely long to look at over 16,000 pixels and work out how many of each material is needed. Or worse, to just keep crafting more materials as you go. Map art is tedious enough. An option to see the number of materials needed would be GREATLY appreciated. I know I don't speak only for myself on this.

**Comment by rebane2001** [comment]
lol there already is a button for this
