### ISSUE TITLE
Issue with button descriptions when changing game versions

### ISSUE THREAD

**Issue by diamondtips** [rebane2001/mapartcraft#105]
When you change the game version under settings from 1.12.2 to 1.16.2 then back to 1.12.2 the button descriptions change from their normal descriptions to 1.16.2 blocks.

Mode description- Crimson Planks
Version description- Crimson Slab
Staircasing description- Crimson Hyphae
Better Color description- Warped Nylium
Blocks to add description- Warped stem
There are more glitched descriptions for all the download buttons.

Images:
![image](https://user-images.githubusercontent.com/71081010/92735694-9f5b2680-f347-11ea-851b-423a126fd376.png)
![image](https://user-images.githubusercontent.com/71081010/92735744-aa15bb80-f347-11ea-981f-09cb36ec27d7.png)
![image](https://user-images.githubusercontent.com/71081010/92735766-ada94280-f347-11ea-8320-32482c1ca05b.png)

**Comment by rebane2001** [comment]
Added in 79ac5832fd25cd76cfae97680fc5ca599f99fcdc
