### ISSUE TITLE
Basalt, Blackstone, Mushroom Stems, and Prismarine Brick Slabs

### ISSUE THREAD

**Issue by crubleigh** [rebane2001/mapartcraft#106]
Basalt and blackstone, blackstone slabs are suitable replacements for black color and should be added to the list. Also, we've been requesting this for a while but it would also be nice to have mushroom stems as a replacement for cobwebs (on the versions this works obviously). Another important one is prismarine brick slabs, a cheaper material than prismarine bricks.

**Comment by rebane2001** [comment]
Please refer to the mushroom stems Issue and help me out if you actually want it

**Comment by crubleigh** [comment]
1.13+ Mushroom stems should show up as the same color as cobwebs. Do you need screenshots from each version?

**Comment by crubleigh** [comment]
Here are some screenshots I took, it would appear that mushrooms conflate with cobwebs starting in 1.14, not 1.13. I've included the Prismarine brick slabs, basalt, blackstone, and blackstone slabs as well. https://imgur.com/a/eOAlNuf

**Comment by crubleigh** [comment]
More data on mush stems for 1.16.3,

**Comment by SelfAdjointOperator** [comment]
I have added Mushrooms (and many other blocks) in commit f58ad5d1f28c412f3a11713074e018d33ab632bf of my fork; these can be implemented and this issue can be closed once the rest of the fork is fully operational.

**Comment by rebane2001** [comment]
Added in #168
