### ISSUE TITLE
Limit staircasing height

### ISSUE THREAD

**Issue by crubleigh** [rebane2001/mapartcraft#107]
I'm sure you've seen jka's 2 layer map with the carpets and solid blocks so it's still mostly "flat." I like this idea a lot, I think it would be a cool option for mapartcraft. Expanding further than just carpet though, the concept could simply be made to "maximum staircase height" A flat map would be a 1, jka's map would be a 2, etc. Shorter staircased maps would be easier to build than full-ass staircased maps and provide something of an in-between as far as difficulty and image quality. 
https://imgur.com/a/Cr4iCdn
Here's a screenshot of the screenshot of the map in question along with his little blurb.

**Comment by rebane2001** [comment]
I'm not sure how I'd write an algorithm to do that, you have any ideas?

**Comment by rebane2001** [comment]
I'm going to close this issue unless you can come up with an algorithm. You can still create dual layer maps with the normal staircasing option if you make the image correctly in the first place.

**Comment by crubleigh** [comment]
You could ask jkascpkmc#1350  if he might share the program he wrote to make his map with you.
