### ISSUE TITLE
WorldEdit compatability?

### ISSUE THREAD

**Issue by JasonGoemaat** [rebane2001/mapartcraft#108]
I haven't been able to get the generated files to work with WorldEdit.  It seems to expect a .schem file for a schematic when doing `//schem load <file>`.  I've tried usign the .nbt suffix with the files generated by this and renaming as .schematic.  WorldEdit gives a format error reading the file (both nbt and dat downloaded and tried).   Any chance of adding support?

I've attached `fallout.nbt` downloaded from the site and `beacon.schem` which was saved with WorldEdit using `//schem save beacon` in a zip file.

[issue.zip](https://github.com/rebane2001/mapartcraft/files/5273264/issue.zip)

**Comment by rebane2001** [comment]
Schematica support will not be added
