### ISSUE TITLE
Add an option to show chunk borders in the view online section

### ISSUE THREAD

**Issue by Jack123456789009** [rebane2001/mapartcraft#110]
splitting the image into more manageable chunks would make it easier to copy directly off the website, especially building in survival

**Comment by rebane2001** [comment]
Yes definitely, I planned on adding this but forgot about it, thanks for creating the issue

**Comment by Jack123456789009** [comment]
Thanks man, currently working on a map art on a server where i cant access the files or anything so this would be a huge help

**Comment by rebane2001** [comment]
Added in 686b084bfa997fb66983064fe88938fd31843eff
