### ISSUE TITLE
Auto-refresh materials

### ISSUE THREAD

**Issue by rebane2001** [rebane2001/mapartcraft#111]

**Comment by rebane2001** [comment]
Not adding due to performance concerns

**Comment by rebane2001** [comment]
However it might make sense to add an auto-refresh checkbox so I'll leave this issue open

**Comment by rebane2001** [comment]
However it might make sense to add an auto-refresh checkbox so I'll leave this issue open

**Comment by rebane2001** [comment]
However it might make sense to add an auto-refresh checkbox so I'll leave this issue open

**Comment by rebane2001** [comment]
Thanks, GitHub

**Comment by SelfAdjointOperator** [comment]
yooooo

**Comment by rebane2001** [comment]
Added in #168
