### ISSUE TITLE
Add info to FAQ about inconsistencies between browsers when JPEG or wrong sizes

### ISSUE THREAD

**Issue by RUBlCON** [rebane2001/mapartcraft#115]
Not a huge issue but I noticed today that even with identical image/settings/blocks selected I'm getting slightly different results on phone and pc, and also between different browsers on the same device. Each Block Amount will vary between browsers by maybe a couple of percent, and the View Online Prototype will also have a fair number of differences. Notably I get the exact same result every time when I redo the same settings and image on the same browser, so it doesn't seem I'm making a mistake. This has only come up as a slight inconvenience because I prepared the materials I needed for a 2x2 based on the result I got on the Chrome mobile app, but the View Online Prototype feature currently doesn't quite show up properly on there, so to know how to build it I need to use that on Google Chrome PC where it works but the map and block amounts are all different. Ultimately this is something I can work around and this is a fantastic tool, but I just thought it was worth pointing out. Thanks for creating this and continuing to support it!

**Comment by rebane2001** [comment]
All devices/browsers should provide identical output on identical input. However, if you upload an image with the wrong size, your browser will rescale it, not the website, so then you might experience inconsistencies. If you can prove the output is different in any other circumstance, please let me know. Otherwise, I'll be closing this issue.

**Comment by RUBlCON** [comment]
Thank you for getting back so fast. However I've rescaled the image to 256x256 and the problem persists. Screenshots are of Chrome and Samsung Internet with same input but different material amounts visible. Also attached the input image used

![Screenshot_ChromeMapArtCraft](https://user-images.githubusercontent.com/72320285/95002912-214e1080-05d1-11eb-9067-e1bccee7a933.jpg)
![Screenshot_SamsungInternetMapArtCraft](https://user-images.githubusercontent.com/72320285/95002915-24e19780-05d1-11eb-8ddb-24bba917b912.jpg)
![256x256resizeMapArtCraft](https://user-images.githubusercontent.com/72320285/95002918-2a3ee200-05d1-11eb-9e26-ed25952ea544.jpg)

**Comment by rebane2001** [comment]
For these kinds of things, please use a PNG, not JPEG. Different browsers process JPEG slightly differently. Once I converted this image into PNG it looked identical everywhere. 

A pro tip is to right click -> save image on the MapartCraft after you have selected your blocks - this way it will always stay the same, even after an update.

**Comment by RUBlCON** [comment]
Perfect, that's sorted then, my mistake. You've been very helpful and the site is fantastic, so I've sent a donation your way :)

**Comment by rebane2001** [comment]
Thank you for the donation!

**Comment by rebane2001** [comment]
actually lemme reopen this so I can add this info to FAQ

**Comment by rebane2001** [comment]
Added in 04d2b520127a65005108cbe5e6fdb4d87661040f
