### ISSUE TITLE
Feature request: new staircasing options

### ISSUE THREAD

**Issue by Optibinds** [rebane2001/mapartcraft#119]
add two new options in staircasing, one to make the map full bright, one to make the map full dark, like that, people will make easy bright maps without hard staircasing, thank you.
![2020-10-17_16 53 58](https://user-images.githubusercontent.com/73082235/96388240-93ad1c00-119f-11eb-9755-f33c236723b2.png)
![2020-10-17_16 54 05](https://user-images.githubusercontent.com/73082235/96388243-99a2fd00-119f-11eb-912d-7098147af79d.png)

**Comment by BangCryDie** [comment]
+1

**Comment by SelfAdjointOperator** [comment]
![2021 09 27_15 36 10](https://user-images.githubusercontent.com/66702639/134930086-ae98b80b-345a-4db5-abce-323455be8c00.png)

This seems to be the correct way to do it, add a checkbox which enables the extra staircasing modes, WIP
