### ISSUE TITLE
Incompatibility with Litematica for Minecraft 1.16.2

### ISSUE THREAD

**Issue by cpage192** [rebane2001/mapartcraft#120]
After downloading a file as an NBT file, I attempted to load the schematic into my world. I expected it to need to convert from ".nbt" to ".litematic", which I have seen it successfully do in the past, but the conversion resulted in a volume the size of the map with 0 blocks inside. Attached is the image I'm trying to recreate. The end-goal is a ludicrously sized map, but I can't even get a 1x1 map to work.

Thank you for your efforts, keep up the good work :)
![paint](https://user-images.githubusercontent.com/25377721/96681643-a06b7480-1345-11eb-9f9f-48bdffdb5c67.jpg)

**Comment by rebane2001** [comment]
Are you on the latest version?

**Comment by cpage192** [comment]
I am using the lastest version of MapartCraft, but I have not taken the time to update Litematica from 1.16.2, so I asked for the file to be produced for 1.16.2.

**Comment by rebane2001** [comment]
Are you on the latest 1.16.2 Litematica?

**Comment by cpage192** [comment]
I am using litematica-fabric-1.16.2-0.0.0-dev.20200812.031039, which it turns out is 11 days older than the newest version. I'll try that version when I have more time, and I'll let you know if it works. Thank you for your quick responses.

**Comment by cpage192** [comment]
I updated to the newer Litematica version and everything works perfectly. I'm not sure what was causing the issue, as I have used MapartCraft with that version in the past, but I don't suppose it matters at this point. Thank you for helping me identify the solution!
