### ISSUE TITLE
Large image

### ISSUE THREAD

**Issue by Polarbub** [rebane2001/mapartcraft#121]
When I goto make a map nbt of my image ![pm884zpfbfu51](https://i.redd.it/pm884zpfbfu51.jpg) at 25 * 19 maps the website crashes at 99 percent saying aw snap out of memory. It works when I only download then as one map per nbt file. I have had success by splitting the image into 5 parts.
![Capture](https://user-images.githubusercontent.com/71790726/96800867-fe429f80-13cb-11eb-87c7-07ca9ef0c690.PNG)
Also when in 3d mode the program doesn't recognize that the max map height is 255 not 256.

**Comment by rebane2001** [comment]
Mfw. Download as split or download as map.dat. I don't see why you'd want to DL it all in once piece as a nbt?

**Comment by Polarbub** [comment]
When the nbts are split up ridges are created. These cast shadows on the first row of the next map over and make big maps look bad.

**Comment by rebane2001** [comment]
You can build them horizontally next to each other. ALSO USE MAP.DAT.
