### ISSUE TITLE
Unable to convert NBT files to Schematic files properly for any version after 1.12

### ISSUE THREAD

**Issue by Sequentilian** [rebane2001/mapartcraft#125]
MCEdit and Cubical are both pre-1.13 Minecraft editors. Any block from a future update either causes an error, or- in cubical's case- shows up as stone and completely ruins the entire image. 

Original image:
![image](https://user-images.githubusercontent.com/74772174/99803181-ba86b580-2b84-11eb-9447-78afb160dfa0.png)

Mapartcraft conversion: (Staircasing off, using Floyd-Steinberg dithering)
![image](https://user-images.githubusercontent.com/74772174/99803190-be1a3c80-2b84-11eb-8c48-db4ff10cac05.png)

Result from converting to .schematic using cubical.xyz:
![image](https://user-images.githubusercontent.com/74772174/99803345-020d4180-2b85-11eb-8517-176c2fedd48d.png)
![image](https://user-images.githubusercontent.com/74772174/99803350-046f9b80-2b85-11eb-8a1f-eaf87351f50f.png)

Unless Cubical or MCEdit somehow upgraded to 1.13+ (Hopefully up to 1.16, if they're still being worked on at all), there's no way of converting a 1.13+ NBT file into a sponge schematic. I know this is more of a problem about external tools than it is about Mapartcraft, but this is a bit of a request to consider support for downloading schematic files straight from your website too.

**Comment by rebane2001** [comment]
If you want a format other than nbt/structure, then it's up to you to figure out how to convert it.

**Comment by Sequentilian** [comment]
Why would NBT be the preferred option? .schematic files are almost universally used more than NBT. If I'm wrong on this, then what's the most popular case of someone using NBT to generate structures?

**Comment by Sequentilian** [comment]
> If you want a format other than nbt/structure, then it's up to you to figure out how to convert it.

Why would NBT be the preferred option? .schematic files are almost universally used more than NBT. If I'm wrong on this, then what's the most popular case of someone using NBT to generate structures?

**Comment by rebane2001** [comment]
Minecraft natively supports reading/writing NBT, it does not support .schematic. In addition, .schematic is an outdated format that uses numeric block IDs (deprecated in 1.13!) instead of block names.

**Comment by Sequentilian** [comment]
> Minecraft natively supports reading/writing NBT, it does not support .schematic. In addition, .schematic is an outdated format that uses numeric block IDs (deprecated in 1.13!) instead of block names.

Fair point. Though, I wanted to make it a generatable structure in Worldedit, which only supports Sponge or MCEdit Schematics. After this, I would manually convert all the cobwebs into Mushroom stems since Mushroom stems are the same colour as of 1.13+. It's also just an easier way for me to look at staircase method maps instead of using litematica's transparent hologram.

**Comment by rebane2001** [comment]
You can export maps as 1.12 and then convert them to .schematic in Cubical. However, you will not be able to use the new 1.16 nether block colors this way.

**Comment by Sequentilian** [comment]
> You can export maps as 1.12 and then convert them to .schematic in Cubical. However, you will not be able to use the new 1.16 nether block colors this way.

So how does one get a physical version of a staircase map art with 1.16 blocks included? If there isn't any way to do it right now, shouldn't one be made for those who need it? Also, mushroom stem is missing from your colour list. There's been a few tickets about this, and even documentation on the Minecraft wiki listing it as the same colour as cobwebs: 
https://minecraft.gamepedia.com/Map_item_format#Map_colors

If I can't get a physical structure with 1.16 blocks, can mapartcraft at least be updated with mushroom stem as an alternative to cobwebs? Yes, I could just use 1.12 blocks, but this breaks colour depth. Yes, I could just use the NBT file as-is, but then it'll tell me to use cobwebs. Is it possible for one or the other be done?

**Comment by rebane2001** [comment]
1.12 blocks don't break color depth lol. You can use the nbt file with litematica or a structure block. Mushrooms stems are out of the scope of this issue.

**Comment by Sequentilian** [comment]
> 1.12 blocks don't break color depth lol. You can use the nbt file with litematica or a structure block. Mushrooms stems are out of the scope of this issue.

Well, I mean it _reduces_ colour depth, but I want to get the most out of map art. I could do it with a structure block though, sounds reasonable enough, just need to download the chunk-by-chunk splits instead because of structure block limits. I assume that last comment is a way of telling me me to open up a separate ticket for this, adding to the other ones regarding the mushroom stem? It was relevant because it's the only major reason I wanted to get a physical loaded version of my map art.

**Comment by Gabocota** [comment]
Sorry but there's no public way of converting such file to .schem or .schematic and minecraft just loads an empty cube when loading the .nbt file directly
