### ISSUE TITLE
Stone schematic

### ISSUE THREAD

**Issue by Domiksxx** [rebane2001/mapartcraft#139]
Hello its my first time using mapartcraft soo i still how to fix issues . idk why the schematics that i create just turns to stone heres a picture

![image_2021-02-03_100621](https://user-images.githubusercontent.com/78457156/106687629-76de0c80-6607-11eb-980e-1a711c3ccff2.png)

**Comment by D4rKT1mmy** [comment]
i do have the same problem

**Comment by rebane2001** [comment]
You are exporting as the wrong version. Please read the FAQ.
