### ISSUE TITLE
Veiw online won't load whole image

### ISSUE THREAD

**Issue by Dark-Nidus** [rebane2001/mapartcraft#142]
I've been trying to use the "view online", trying make a staircase map on console. But it only loads the upper Left hand corner about 144 blocks or so of the blocks...

**Comment by rebane2001** [comment]
If you zoom out it's still cut off? Please send screenshots.

**Comment by Dark-Nidus** [comment]
I've tried on both my pc and my phone, neither can be loaded out any further... And my pc saves it as it appears.
![download (1)](https://user-images.githubusercontent.com/78912333/107641728-92fe3100-6c39-11eb-8b26-a7b0e5701711.png)
![Screenshot_20210211-071244](https://user-images.githubusercontent.com/78912333/107641768-a1e4e380-6c39-11eb-8c8b-f5cb761ca5bb.png)

**Comment by rebane2001** [comment]
Can you like, zoom out and then send a screenshot?

**Comment by Dark-Nidus** [comment]
Like how do you mean?

**Comment by rebane2001** [comment]
Scroll out

**Comment by Dark-Nidus** [comment]
That fixed it... Thanks
