### ISSUE TITLE
Color block suggestion: Void color for ultimate dark

### ISSUE THREAD

**Issue by kgftbz** [rebane2001/mapartcraft#147]
I usually build maps on large empty areas of the End dimention, and the void background in the map seems darker than the black color in it's darkest staircasing, so maybe a new color option for void could be added to be used as a new darker black.
This option would just not place any block in the place that would use the void's black.

**Comment by Nr1Princess** [comment]
at least for all the versions i play void has the same grey color as bedrock/stone. what version of minecraft are you using that void is black?

**Comment by rebane2001** [comment]
I'd like to hear the same information as Nr1Princess asked for. Please provide more details.

**Comment by kgftbz** [comment]
Oh my bad, I was looking at a bedrock edition map.
Unfortunally they're a bit diferent
