### ISSUE TITLE
Conrete not working

### ISSUE THREAD

**Issue by bobodabodog** [rebane2001/mapartcraft#148]
All schematics convert to just white concrete when put into cubical, i am exporting as 1.12.2.
Its only with concretw but i dont qanna have to get the stone

**Comment by rebane2001** [comment]
Is this a cubical-specific issue?

**Comment by bobodabodog** [comment]
I don't believe so i can't install things on the pc without asking as its my dads

**Comment by rebane2001** [comment]
I'll close it since there is no evidence of it being broken in-game.

**Comment by bobodabodog** [comment]
Ok
