### ISSUE TITLE
problem with the viewing online option

### ISSUE THREAD

**Issue by badbuddhajack** [rebane2001/mapartcraft#151]
when viewing online to see the cords and block patterns and map that is a 2:2 or higher wonts show up and it tells you that your are looking at a block that is way out of the map size

**Comment by rebane2001** [comment]
Keeping this open because it still affects the old 2D view and it'll probably get ported back at some point

**Comment by SelfAdjointOperator** [comment]
Fix merged in fdd6f955367011afd6db3c369b393c0b51bb1967
