### ISSUE TITLE
Mushroom stem not included as alternative for cobweb

### ISSUE THREAD

**Issue by Delukasor** [rebane2001/mapartcraft#154]
Mushroom stem not included as alternative block for cobweb.
![asdfasdf](https://user-images.githubusercontent.com/72415494/113220608-794c9380-9251-11eb-9153-41fc7e1cc484.png)

**Comment by Delukasor** [comment]
the brown part on the left part of the right square is still mushroom stems, i just added->removed some mushrooms blocks to expose the brown texture to see if that would change anything - it did not

**Comment by SelfAdjointOperator** [comment]
I have added Mushrooms (and other blocks) in commit `f58ad5d1f28c412f3a11713074e018d33ab632bf` of my fork; these can be implemented and this issue can be closed once the rest of the fork is fully operational.

**Comment by rebane2001** [comment]
Added in #168
