### ISSUE TITLE
Replacing a bunch of block with stone?

### ISSUE THREAD

**Issue by K-Denki** [rebane2001/mapartcraft#156]
I'm not sure if this is something to do with just me, or if anyone else has this problem.
The preview of the mapart looks fine on the website, but when I download the .nbt file, it replaces a bunch of the blocks with stone, and ends up looking like this?
Is there any specific things I need to select to stop this from happening?
It worked fine for me a few days ago...
![Screenshot 2021-04-17 141818](https://user-images.githubusercontent.com/81511691/115114539-d81b4800-9f87-11eb-8436-b0793ce338e0.png)

**Comment by rebane2001** [comment]
Please read and follow the FAQ carefully. If that doesn't help, then reply with more details and I'll reopen the issue.

**Comment by K-Denki** [comment]
I read the FAQ, I couldn't find anything in there that could necessarily fix this issue. 
Lets say for instance, I chose all carpets. This is what the image render looks like.
![Screenshot 2021-04-18 143158](https://user-images.githubusercontent.com/81511691/115147442-e2eedf00-a052-11eb-84b5-d20f631e2fae.png)
However, when I open it, there's nothing but stone! I think it might have something to do with the carpet blocks?
![image](https://user-images.githubusercontent.com/81511691/115147472-0dd93300-a053-11eb-9bfa-62bf8e4031e4.png)

**Comment by rebane2001** [comment]
What are you using for the second screenshot?

**Comment by K-Denki** [comment]
I'm using cubical.xyz!

**Comment by rebane2001** [comment]
Why do you have 1.16.5 selected on the first screenshot?

**Comment by K-Denki** [comment]
_Sorry for taking so long to reply my power has been out for a while-_
Well, it's because I'm using 1.16.5 Minecraft!
It seemed to work with that version selected previously so I'm not sure why that would be the problem, but you most definately know a lot more about this than me, haha
