### ISSUE TITLE
can we get basalt for black color

### ISSUE THREAD

**Issue by rasmus123d** [rebane2001/mapartcraft#161]
same as title

**Comment by SelfAdjointOperator** [comment]
Added in my fork commit 2a1ff66a9975fcef16548b5f84440aeb4ec8aac4

**Comment by Sicarine** [comment]
Have you considered adding Pumpkins as an orange alternative to your fork? Pumpkins are real easy to farm and a perfect block for huge maps.

**Comment by SelfAdjointOperator** [comment]
Pumpkins seem like a good idea

**Comment by SelfAdjointOperator** [comment]
Added in 2eea49d432e33d088f17340d5353c8980e64002b

**Comment by rebane2001** [comment]
Added in #168
