### ISSUE TITLE
1.17 Support: Two New Map Colours

### ISSUE THREAD

**Issue by Sicarine** [rebane2001/mapartcraft#164]
In snapshot 21w15a, as part of the fix for MC-215836, Mojang made Deepslate a different shade from any other shade of gray or dark gray.

_Edit: Apparently they also updated the deepslate ore variants to be the same colour as deepslate, distinct from stone_

Similarly, in snapshot 21w16a, as a part of the fix for MC-212863, Mojang made Glow Lichen a unique shade distinct from any other similar cyan or aquamarine shades. 

See attached screenshot.
![2021-04-22_20 40 31](https://user-images.githubusercontent.com/43017668/121444918-542e7c80-c988-11eb-8ff4-1f1145595deb.png)

Edit: Checked for changes in 1.17 full release. Deepslate Ore variants are now the same colour as deepslate
![2021-06-11_16 57 11](https://user-images.githubusercontent.com/43017668/121714984-4e46b180-cad6-11eb-81a3-481e423c849b.png)

**Comment by SelfAdjointOperator** [comment]
Would it be best to let 1.17 mature a couple of minor versions first? 1.16's colours changed a couple of minor versions in ( see #140 )

**Comment by Sicarine** [comment]
Yea, worth keeping an eye on.

Meanwhile, I'll put a list here for the new 1.17 blocks and what colours they appear to be mapped to. People can check against this list come the next minor release and see if there are any changes:

- Deepslate and its ores: new (unique)
- Glow Lichen: new (unique)
- Moss: green, dried kelp, etc 
- Azalea + Dripleaf: plants, etc.
- Tuff: Gray Terracotta
- Calcite: White Terracotta
- Amethyst: Purple, bubble coral, etc.
- Raw Iron: White Terracotta
- Raw Gold: Gold
- Raw Copper: Orange, acacia planks, etc.
- Rooted Dirt: granite, jungle planks, coarse dirt, etc.
- Copper: orange, etc
- Exposed Copper: Light Gray Terracotta
- Weathered Copper: Warped Planks
- Oxidized Copper: Warped Nylium
- Tinted Glass: Gray Concrete
- Sculk Sensor: Cyan
- Dripstone Block: Brown Terracotta

**Comment by SelfAdjointOperator** [comment]
Oh wow that's actually a lot more blocks than I was expecting, exciting stuff. Thank you!

**Comment by SelfAdjointOperator** [comment]
I'm noticing Deepslate (and friends) showing up as mapdatId 59 and Glow Lichen as mapdatId 61. I wonder what blocks use id 60 if anything?
I created a map with those three at the top, and 60 shows up as the second colour down:

![2021-07-10_06 53 57](https://user-images.githubusercontent.com/66702639/125153490-f2f6f600-e14b-11eb-94d5-c7b1446edfb4.png)

Trying to create a map with mapdatId > 61 currently (1.17.1) crashes the game, so it seems to be just these new two possibly three colours.

The [wiki](https://minecraft.fandom.com/wiki/Map_item_format#Color_table) has not yet been updated for 1.17.

**Comment by crubleigh** [comment]
Color 60 would appear to be compacted raw iron blocks.

**Comment by SelfAdjointOperator** [comment]
Ready any time since 2d350f215dc1f3ec4c407448096f4c11100bdc12 . As of writing 2021.07.11 Minecraft is at 1.17.1 and no 1.17.2 is visible. Probably will be deployed soon.

**Comment by Sicarine** [comment]
Did check it to confirm, and yea. That is the subtlest difference, but it's there. Was that there in 1.17.0, I wonder....
![2021-07-11_16 45 02](https://user-images.githubusercontent.com/43017668/125201610-cb954b80-e267-11eb-9fd9-a202cb7bae10.png)

**Comment by SelfAdjointOperator** [comment]
Deployed in 9635ca7995a1d1c78684c069fad78fe4940ca5fa
