### ISSUE TITLE
clay blocks turn grey after downloading

### ISSUE THREAD

**Issue by CrossWay18** [rebane2001/mapartcraft#167]
mapart
![image](https://user-images.githubusercontent.com/70350712/123350918-9bd50c80-d521-11eb-8df5-a1d11e75cb2c.png)
after download
![hmhmhmhm](https://user-images.githubusercontent.com/70350712/123350952-b1e2cd00-d521-11eb-920c-15b3e9473071.PNG)

**Comment by rebane2001** [comment]
Read faq
