### ISSUE TITLE
Hide colors not available in selected version

### ISSUE THREAD

**Issue by ItzDawnfall** [rebane2001/mapartcraft#170]
In the current version of MapartCraft, you can see map colors that don't exist in that specific version. I think it would be a good idea to hide these colors as it would take up less space and possibly avoid any confusion. Could be a toggleable box or could be just automatically not shown.

MC version 1.12.2 selected:
![image](https://user-images.githubusercontent.com/35278501/124409539-5ec90100-dcfd-11eb-8f80-df166c8abcdc.png)

**Comment by SelfAdjointOperator** [comment]
Addressed in c3028d1803305512cc9029ff2fc91be1089c4843
