### ISSUE TITLE
View Online

### ISSUE THREAD

**Issue by TW146** [rebane2001/mapartcraft#171]
Can you keep 2D for online viewing? I’m a bit uncomfortable with 3D images

**Comment by rebane2001** [comment]
You can use the classic version of the site

**Comment by SelfAdjointOperator** [comment]
Added back in 8a619cbcfe00e1991b44a6b9f62cd017756d48ca . Ready soon

**Comment by SelfAdjointOperator** [comment]
Merged in fdd6f955367011afd6db3c369b393c0b51bb1967
