### ISSUE TITLE
Download Probleme 

### ISSUE THREAD

**Issue by GoTChillrich** [rebane2001/mapartcraft#173]
Hey 
Ich habe ein Problem bei den Downloads.
Seid dem neuen Update kann ich nie die kompletten einzelnen schematics downloaden! Es fehlen immer welche.
Woran kann es liegen?

**Comment by rebane2001** [comment]
Please share screenshots and explain your problem more in-depth. Please speak in English.

**Comment by GoTChillrich** [comment]
![Screenshot_20210708-191401_Chrome](https://user-images.githubusercontent.com/87141378/124964143-f5a8fc80-e020-11eb-8b02-eecf835f432e.jpg)
![Screenshot_20210708-191517_Chrome](https://user-images.githubusercontent.com/87141378/124964149-f80b5680-e020-11eb-920c-88c6564a50d4.jpg)

**Comment by GoTChillrich** [comment]
There should be 35 parts and only 17 will be downloaden.
Is unfortunately not only like that for me

**Comment by GoTChillrich** [comment]
Sorry my Englisch ist not good

**Comment by rebane2001** [comment]
Please try on a computer. MapartCraft is not designed for mobile devices.

**Comment by GoTChillrich** [comment]
Its the same on my PC

**Comment by rebane2001** [comment]
Confirmed - we will look into this

**Comment by rebane2001** [comment]
Meanwhile you can use the classic version of mapartcraft  
https://rebane2001.com/mapartcraft/classic

**Comment by GoTChillrich** [comment]
Thanks IT worked with the classic Version!!

**Comment by SelfAdjointOperator** [comment]
Addressed in f1c61bc00e6d6c5106702dddddafc0a4b548782d
