### ISSUE TITLE
Adding a Crop modifier, to change the location of cropped images

### ISSUE THREAD

**Issue by nicolasGEL** [rebane2001/mapartcraft#175]
Currently, it just crops on the center, adding a slider or an offset value to change the center point of the crop would be useful

**Comment by SelfAdjointOperator** [comment]
Addressed in 0d7a6772ad50df01142209c153dfd65aedeca58d
Ready in a couple more commits

**Comment by SelfAdjointOperator** [comment]
![Crop 2021 07 15 21 01 00 trim](https://user-images.githubusercontent.com/66702639/125853206-edfcd552-413c-49ba-9da9-d3fe5869c434.gif)
Average Mapart enjoyer

**Comment by nicolasGEL** [comment]
pog
