### ISSUE TITLE
1.17 compatible 

### ISSUE THREAD

**Issue by dat1boiatschool** [rebane2001/mapartcraft#177]
Since as 1.17 part 1 has came out there is new blocks and colour varieties but as of now there has not been any version of mapartcraft compatible with 1.17. I fear that if I still try to use version 1.16.5 it may corrupt or even delete my world in worst cases. If 1.17 why not make it compatible with it.

**Comment by SelfAdjointOperator** [comment]
Added / merged in 85042b8a0cca0bd48182b563de7bb2114e5ece03
