### ISSUE TITLE
The image for dark oak planks and dark oak slabs is swapped

### ISSUE THREAD

**Issue by littlebugman** [rebane2001/mapartcraft#183]

**Comment by SelfAdjointOperator** [comment]
Good catch! PR #184 opened.

**Comment by SelfAdjointOperator** [comment]
Git blame leads to d5289107a523a697e422ea27f58bc853434bc165 , human error at [this](https://github.com/rebane2001/mapartcraft/commit/d5289107a523a697e422ea27f58bc853434bc165#diff-1bc88bdab9fe45c14ae0ec9d16471188303766cb33b7356d913f0ed7e931e8beL3232) diff, generated by [this](https://github.com/rebane2001/mapartcraft/commit/d5289107a523a697e422ea27f58bc853434bc165#diff-b9910a66e1d8a5daf8518fa0137e9571f3d18af85efbd2cb268c0f24dcbe1a83R663) ordering

**Comment by SelfAdjointOperator** [comment]
Merged
