### ISSUE TITLE
Not Bug.

### ISSUE THREAD

**Issue by JackTGG** [rebane2001/mapartcraft#188]
I think you should add making it into a litematica schematic, I am Pretty sure it would not be that hard. you would just make The Inf o About it set to MapCrafter and then translate the blocks in and then make it into a file and loaf it like normal.

**Comment by rebane2001** [comment]
You can use the .nbt file with Litematica

**Comment by ToKiNoBug** [comment]
> I think you should add making it into a litematica schematic, I am Pretty sure it would not be that hard. you would just make The Inf o About it set to MapCrafter and then translate the blocks in and then make it into a file and loaf it like normal.

Making litematica schematic is harder than .nbt. Litematica schematics use a bit-squeezing method (up till now i still failed to understand it) to store blocks like a dense 3d array, while .nbt stores like a sparse index 3d array.
