### ISSUE TITLE
Inaccurate staircasting to water

### ISSUE THREAD

**Issue by ToKiNoBug** [rebane2001/mapartcraft#197]
I see that water blocks are staircasted like solid blocks, however water's shade doesn't work like solid blocks. Shade of water blocks are determined by their depth instead of surrounding blocks. (1.16+ tested)

**Comment by rebane2001** [comment]
If you hover over water you will see it says "unsupported".

**Comment by ToKiNoBug** [comment]
Well....., will they become supported in future? just process them specially apart from other blocks: single water block for shade 2, 6 in a column for shade 1 and 11 for shade 0

**Comment by rebane2001** [comment]
Not sure. It's harder to implement than it seems, especially for staircased maps, because you need to prevent the water from flowing out by placing glass or something around it. It's possible but I don't plan on adding it in the near future.
