### ISSUE TITLE
Y level numbers can't be read on white-colored blocks

### ISSUE THREAD

**Issue by Carmen14edo** [rebane2001/mapartcraft#198]
I'm working on a map art with many colors in it, but the background is white, and the majority of the pixels are white. I'm using staircasing but I can't read most of the numbers written on the blocks since a majority of the blocks are white and the font is also white. Hoping maybe someone could update it so the y level font color is dependent on what shade of block that pixel is. It'd be much appreciated.

**Comment by rebane2001** [comment]
Added in 177f405e56412942d9955242e1cfcd25736abe7a
