### ISSUE TITLE
Add Concrete Powder to selection

### ISSUE THREAD

**Issue by NintenJoSP** [rebane2001/mapartcraft#21]
I have been making map pixel art on a survival multiplayer server for a couple months now the old-fashioned way and as art gets more complicated it's getting harder to do things without using a schematic. MapartCraft has everything i need to make the big move, except concrete powder isn't an option for block choice and it's what i prefer to use since I reuse the same space for all my art and it's much easier to remove than solidified or wool.

**Comment by rebane2001** [comment]
Good idea, I'll add this soon

**Comment by rebane2001** [comment]
Added in 8bdd187
