### ISSUE TITLE
1.19 Blocks

### ISSUE THREAD

**Issue by Nydaleclya** [rebane2001/mapartcraft#232]
Ochre Froglight -> Same as Sand
Pearlescent Froglight -> Same as Pink Wool
Verdant Froglight -> Same as Glow Lichen

Packed Mud -> Same as Dirt
Mud Brick Slab -> Same as Brown Wool
Mud Bricks -> Same as Light Gray Terracotta
Mud -> Same as Cyan Terracotta

Sculk, Sculk Vein, Sculk Catalyst, Sculk Shrieker -> Same as Black Wool

Mangrove (Planks, Log (vert), Slab) -> Same as Red Wool
Mangrove Log (horizontal), Mangrove Roots -> Same as Podzol

Waterlogged Leaves -> Same as Water

**Comment by rebane2001** [comment]
Added 1.19 in f4b667dd3a4912fac7dcabd9616a2916a8027578, but still need to add the new blocks

**Comment by rebane2001** [comment]
Added the new blocks
