### ISSUE TITLE
New Feature Request Single Map High Resolution

### ISSUE THREAD

**Issue by TheLynx927** [rebane2001/mapartcraft#233]
In minecraft you are capable of making single maps with up to a 512x512 resolution would it be possible to get a map.dat download option for the higher resolution maps.

**Comment by rebane2001** [comment]
It is not possible to make a single map be bigger resolution than 128x128. If you have a method please include proof and reproduction steps.

**Comment by TheLynx927** [comment]
My apologies, after your comment I did some more digging and I misunderstood the way they handle the expanded maps. Thanks for your quick response.
