### ISSUE TITLE
QR codes sometimes not having the right angles of the original image

### ISSUE THREAD

**Issue by 0n** [rebane2001/mapartcraft#234]
this image
![qrcode(1)](https://user-images.githubusercontent.com/45835056/177646199-6f110527-6b16-4f37-a74d-f5e08e13e32d.png)
results in this image/map/preview
![image](https://user-images.githubusercontent.com/45835056/177646140-2bee7773-92dc-449c-8238-96e370227f16.png)
despite all being clear black on white right angles there's some rounded corners for no reason

**Comment by rebane2001** [comment]
You need to scale your original image to 128x128 resolution correctly beforehand if you want it to be pixel-perfect
