### ISSUE TITLE
Selecting a Preset and clicking Delete completely removes the Preset

### ISSUE THREAD

**Issue by zrust-1** [rebane2001/mapartcraft#237]
I was using the "Everything" preset for the block selection and when I clicked Delete, the preset to use was totally gone. I tried refreshing and restarting my browser/PC but nothing worked. Does this have something to do with cookies or could this be another issue? 

Thanks.

**Comment by rebane2001** [comment]
This is intended behavior. Deleting a preset does indeed delete it. You can either recreate it or clear your cookies.

**Comment by zrust-1** [comment]
> This is intended behavior. Deleting a preset does indeed delete it. You can either recreate it or clear your cookies.

My mistake, thank you
