### ISSUE TITLE
Mapart Bug

### ISSUE THREAD

**Issue by adabugra** [rebane2001/mapartcraft#253]
![image](https://user-images.githubusercontent.com/57899270/221955623-cb30d725-7f38-43a4-9ae0-747a359b88e7.png)
![image](https://user-images.githubusercontent.com/57899270/221955649-ef260063-fdbb-4fce-ab11-46cd0602190c.png)
why my mapart looks like this 
![image](https://user-images.githubusercontent.com/57899270/221955734-9335f012-6d86-4580-88f9-f88f8cd7b781.png)

**Comment by adabugra** [comment]
![yuh](https://user-images.githubusercontent.com/57899270/221956460-68173d2c-56c8-4bc5-a054-015e7de5b4fb.png)
normal image

**Comment by adabugra** [comment]
![image](https://user-images.githubusercontent.com/57899270/221971574-e969ef66-36b8-4cfd-a8bb-340ccba63ed2.png)
also it works fine on classic version

**Comment by adabugra** [comment]
i think its about image size but when i try with another 256x256 image it doesent looks like this

**Comment by rebane2001** [comment]
Set the map size to 2x2 if you want to use a 256x256 image. The image you sent gets blurry when rescaled to 128x128 for a 1x1 map.
