### ISSUE TITLE
Does this work on ps4 if so how. MapartCraft.com

### ISSUE THREAD

**Issue by Happystarfis** [rebane2001/mapartcraft#257]
Im really struggling to find a way to view the build on the website. Im on tablet and trying to get it to my ps4 bedrock. Is there any way i can get it to show me. It also doesn’t show me when i download it.

**Comment by rebane2001** [comment]
The site is intended to be used on a computer and with Minecraft Java edition. You might be able to make it work on other devices, but it is unsupported and the colors in Bedrock edition might be different.
