### ISSUE TITLE
Mushroom Stem and Cobwebs

### ISSUE THREAD

**Issue by IotaReality** [rebane2001/mapartcraft#30]
Hello,

Mushroom Stem and Cobwebs have the same color on the maps. Please add it to the options for that color.

Thank you - Iota

**Comment by rebane2001** [comment]
[I can't reproduce](https://i.imgur.com/UyoGZKO.png), could you give more information (Minecraft version, screenshots etc)

**Comment by NintenJoSP** [comment]
On 1.15.2 at least, placing mushroom stems with the white part facing up will produce the same colour on maps as cobwebs - I was going to request the same thing and saw this here so thought I'd add to it

**Comment by rebane2001** [comment]
Thanks for the info, I'll look into it. Perhaps I need to add 1.13-only blocks so that the blocks not available in 1.12 can still be used

**Comment by crubleigh** [comment]
Is this what you meant? Here's the screenshots from my more recent post. https://imgur.com/a/eOAlNuf

**Comment by rebane2001** [comment]
Thanks I'll look into it

**Comment by crubleigh** [comment]
More info with the block states in 1.16.3 https://imgur.com/a/2Rk5MXd

**Comment by rebane2001** [comment]
Added in #168
