### ISSUE TITLE
Add soft limit to map size

### ISSUE THREAD

**Issue by rebane2001** [rebane2001/mapartcraft#31]

**Comment by rebane2001** [comment]
This is a "sane" limit (eg 5x5) and trying to go over it will ask the user if they're completely sure they want to do that

**Comment by rebane2001** [comment]
Added in #168

**Comment by rebane2001** [comment]
Doesn't actually seem to have it implemented yet

**Comment by SelfAdjointOperator** [comment]
Is there really a reason for soft limit though? All of the staircase algorithms etc are size-independent so there's nothing backend that could go wrong with arbitrary sizes (famous last words)

**Comment by rebane2001** [comment]
Not really, it used to be because accidentally creating a 128x128 map would crash the site, but it seems to perform relatively well now so I don't think this is a problem any further.
