### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jefferyw08** [rebane2001/mapartcraft#34]
make it so you can export/import a preset as a text url thing so you can share a preset with other people like

yeah use this preset so you can see the terracotta easier /=HJwefwyebf73jehfbwef=/

**Comment by rebane2001** [comment]
This is a good idea, I'm adding this once I finish implementing the UUID system

**Comment by rebane2001** [comment]
Added in 0a01c7ecb3bab2991422398b7a824f72577fedb8
