### ISSUE TITLE
Add 1.13/1.14/1.15 slabs and blocks.

### ISSUE THREAD

**Issue by crubleigh** [rebane2001/mapartcraft#39]
I like to use slabs on all my shit because it works well over ice and doesn't spawn mobs. As of 1.13, prismarine blocks are slabbable, and as of 1.14 all stone-type blocks (diorite, andesite, smooth stone, sandstone etc.) are slabbable as well. I'm sure there are other new blocks like honeycombs and whatnot as well but the slabs are actually useful. Also, I saw it in another post here but in current versions of the game mushroom stems are the same color as cobwebs so that should be an option as well.

**Comment by zprosal** [comment]
Here's a full list of (usable) blocks to add as of 1.15.2: Asterisk denote supporting block required. Parentheses denote blocks from 1.13+.

- Sand: Bone Block, Turtle Eggs (1.13), Scaffolding* (1.14), End Stone Brick Slab (1.14), 
- Cobweb: Mushroom Stem (1.13)
- Redstone: Fire*
- Ice: Blue Ice (1.13)
- Iron: Lantern* (1.14), Grindstone (1.14), Brewing Stand
- Leaves: all flowers*, tall grasses*, ferns*, and small mushrooms*
- Jungle: Granite Slabs (1.14)
- Stone: Gravel, Cauldron, Ender Chest, Stone Bricks, Stone Brick Slab, Smooth Stone (1.14), Stone Slab (1.14), Andesite Slabs (1.14),
- Diorite: Diorite Slabs (1.14)
- Orange: Red Sandstone Slabs, all Pumpkins, Honey Block (1.15), Honeycomb Block (1.15)
- Gray: Acacia Wood, all Dead Coral Blocks (1.13), all Dead Corals* (1.13), all Dead  Coral Fans* (1.13)
- Cyan: Prismarine Slab (1.13)
- Brown: Spruce Sign
- Green: Dried Kelp Block (1.13), Sea Pickle* (1.13)
- Red: Brick Slab, Red Mushroom Block (1.13)
- Gold: Bell (1.14)
- Diamond: Prismarine Brick Slab (1.13), Dark Prismarine Slab (1.13)
- Spruce: Jungle Sign
- Netherrack: Nether Brick Slab, Red Nether Brick, Red Nether Brick Slab (1.14)

**Comment by calebschieck** [comment]
I build lots of maps in survival and use slabs wherever I possibly can too.
One thing I noticed is that the "Stone Slab" option on the web page looks like it would use the new Smooth Stone Slabs, but gives Stone Slabs in the schematic.
Sorry if this isn't quite on topic. Also, thanks for this website. It's super helpful!

**Comment by rebane2001** [comment]
Added in #168
