### ISSUE TITLE
Carpets are missing

### ISSUE THREAD

**Issue by MrJeffOfficial** [rebane2001/mapartcraft#40]
i dont know if this is a issue with litematica but when i try to load the .nbt file the carpets are gone. only the stone blocks that are underneath are here. But when i put normal wool blocks everything is there.

**Comment by rebane2001** [comment]
1. What game version did you pick while creating the schematic?  
2. What game version are you running?

**Comment by MrJeffOfficial** [comment]
1.14.4 but i found out it was litematica doing it cause when i loaded the .nbt file in mcedit the carpets were here.

**Comment by rebane2001** [comment]
This is a glitch that happens when you select the wrong game version in MapartCraft

**Comment by MrJeffOfficial** [comment]
but i was using the 1.13/1.14 setting and running litematica 1.14?
