### ISSUE TITLE
Add an option to download the preview without making it 2x

### ISSUE THREAD

**Issue by Brochacho5** [rebane2001/mapartcraft#41]
Personally I like editing the previews before making the final nbt, but I find it annoying to have the size at 2x, instead of the regular size

**Comment by crubleigh** [comment]
This. And if you try and shrink it back down to map resolution the colors get fucked up.

**Comment by rebane2001** [comment]
The colors don't get fucked up if you downscale it.
That being said, I have the fix, but Google Chrome is broken right now, so I'm waiting to see if they'll fix it

**Comment by crubleigh** [comment]
Maybe it's just because I'm using MS paint but when I shrink an image, even if it's been perfectly scaled it mushes up the colors.

**Comment by crubleigh** [comment]
I tried paint.net to downscale and it also fucks up the color. The other issue is if you go in to edit the image, even keeping in mind that 2x2=1 pixel, if you go off of the grid at all, you are then between pixels and it fucks it up hardcore if you try and put it back through.

**Comment by rebane2001** [comment]
Paint.net downscale works just fine, are you sure you're using it correctly? Try setting it to nearest neighbor scaling mode (you shouldn't have to, but it should definitely work)

**Comment by rebane2001** [comment]
Added CSS scaling in 5f7a5ba42919023476be15d71be084c259bcf425 (image will be 2x in the browser, but if you right click and copy image, it will be 1x)
