### ISSUE TITLE
Map Art Generator Doesn't Choose Colours Closest To The Image

### ISSUE THREAD

**Issue by rsgsgsgsg** [rebane2001/mapartcraft#44]
I was playing around with your website when I noticed that when I used the 'Carpet Only' preset the preview would turn out orange instead of red.

However, when I disable 'Orange Carpets' it will switch to using red carpets, which look much closer to the original image. It always had the option to use red, but instead opted to use orange.

Original 128x128 Image:

![Original Image](https://user-images.githubusercontent.com/60695741/73838274-e62eee00-4845-11ea-8f42-b87050742b41.png)

Carpet Only Default Generated Schematic:

![Generated Schematic](https://user-images.githubusercontent.com/60695741/73838330-0a8aca80-4846-11ea-9348-9a141aee37f8.png)

'Fixed' Schematic (Carpet Only with Orange Carpets Disabled):

![image](https://user-images.githubusercontent.com/60695741/73838567-8b49c680-4846-11ea-8388-6fd25bfb5797.png)

As you can see, the second schematic generated looks much closer to the original, but the schematic that is generated by default utilises orange carpets rather than red.

**Comment by rebane2001** [comment]
The "non-fixed" version is actually more correct. You could try toggling the "Better colors" option to see a different result. If you wish to have a specific color, edit your image beforehand.

This is not a bug, just your mind playing tricks on you.

**Comment by rsgsgsgsg** [comment]
Better Colours does not change it. If the orange one is technically closer to the original then there is no bug, just looks kinda weird to me.
