### ISSUE TITLE
Height increase for same color/block?

### ISSUE THREAD

**Issue by phoenixlzx** [rebane2001/mapartcraft#48]
Hi,

We found the 3D map increases block height by 1 when there are same blocks connected. Is this intended behavior or it's a bug?

Please check the picture:

![20200218010049](https://user-images.githubusercontent.com/1400198/74669410-6a8c5400-51ea-11ea-996a-254824f2450b.png)

Thank you in advance.

**Comment by rebane2001** [comment]
This is not a bug
