### ISSUE TITLE
Limit staircasing height

### ISSUE THREAD

**Issue by Valericoe** [rebane2001/mapartcraft#52]
Currently generating a large bright map requires placing blocks above y=255.

![image](https://user-images.githubusercontent.com/43940984/78381319-31921e00-75a3-11ea-9423-81ac8499f6cd.png)

In this instance a 3x2 map starts at y=2 and is cut off at y=255.

**Comment by Valericoe** [comment]
One solution to this for **bright** maps would be post-processing on each staircase to detect if the height is over 250 blocks (given that bedrock starts at layer 4).
If so, start at the end of the staircase and follow it down until a rising block is found (A/C) or until 250 blocks are checked.
If found move the checked section down to the base of the structure and resume checking the staircase for a height greater than 250.
If not found move the checked section (1x250x250) to the base of the structure, resulting in a single dark block instead of a blank area.

![image](https://user-images.githubusercontent.com/43940984/78381893-00feb400-75a4-11ea-8ae1-3c4cc98c6805.png)

Going from the end to the beginning rather than the other way solves the more common case C as well as case A without needing to follow the staircase down as well.

**Comment by Valericoe** [comment]
Additionally, for dark maps the process could be repeated with minor changes.
If a staircase's height is determined to be greater than 250 blocks, start at the beginning (y=355) and follow the staircase down until an ascending block is found or 250 blocks are checked.
If found, move the checked section down and check if the staircase is still over 250 blocks - If so, resume else break.
If no ascending block is found move the entire (1x250x250) section down such that a single light block is created.

**Comment by rebane2001** [comment]
Hey, for now I recommend downloading the map as 1x1 split, this gets rid of all the height-related problems.
I do plan on adding this feature you're looking for at some point, but not before I rewrite how the maps are formed

**Comment by Valericoe** [comment]
That works, thank you.

Thanks again for the tool. I've created a few maps with this in survival and they're great.

**Comment by rebane2001** [comment]
I'm happy enough with the solution in ec024c6652ce624374b73794901cba0144b1860a, so I'll be closing the issue
