### ISSUE TITLE
Suggestion: Only staircase up, all valleys start at the base level

### ISSUE THREAD

**Issue by TheRooster13** [rebane2001/mapartcraft#56]
In survival, building staircases up is easy. Building staircases down is hard/impossible. If every valley (low point with staircases up on both sides) started at the base layer, building would be much easier. It would also limit the build height as much as possible without having to touch the color selection algorithm.

The image below is supposed to represent a north-to-south slice using the same block. The shade of each block represents the darker or lighter shade caused by the staircasing. So black blocks have a block higher than them immediately to the north. Light grey blocks have no block higher or level with them immediately to the north. Dark grey blocks have a block level with them immediately to the north. White area is air.

![Valleys_to_base](https://user-images.githubusercontent.com/19157124/80312072-7a9f5180-87a0-11ea-8b5b-2f9448580f1f.png)

**Comment by rebane2001** [comment]
Thank you for your thorough suggestion and explanation, it seems like a great idea

I'll probably look into implementing this after I finish the vanilla/visual-mode for MapartCraft

**Comment by TheRooster13** [comment]
Awesome. Your tool is great! I made my own visual mode by manually limiting the number of colors, then remapping the colors to easily distinguishable colors in Gimp., Then scaling the image up without interpolation, then adding a grid. It was a pain, but do-able. Alternately I could have made multiple images, one for each color. Or maybe have a few colors in each image.

Then I installed Litematica and got it working. Turned out to be pretty easy and client-side only.

**Comment by TheRooster13** [comment]
I took a stab at modifying your code to only staircase up. I haven't created a build environment so I'm unable to test these changes, but since they're not too terribly huge, I think it has a good chance of compiling and working. ;) I haven't programmed in Javascript in years, so there might be some syntax errors.

Basically, during the first pass through each column, it records the heights of each local peak and valley into an array. Then during the second pass, instead of initially shifting the entire column by the absolute minimum and the underblock adjustment factor, it first determines the correct local base, and then when writing to the schematic, it adjusts the height by the base and the adjustment factor.

Let me know if you have any questions. I think this is worth implementing even before getting the vanilla/visual-mode working because hopefully it will make more portions of the schematic reachable from ground level, which will make building and erasing maps much faster, even when using a schematic. At least in survival.

[mapartcraft_app_modifications.zip](https://github.com/rebane2001/mapartcraft/files/4583587/mapartcraft_app_modifications.zip)

**Comment by rebane2001** [comment]
Thank you for the code, it seems promising! I'll take a deeper look at it later and implement it into the project

**Comment by rebane2001** [comment]
Your code did not work, but it provided a good starting point. There were a lot of small problems (overall, not in your code) that took me about 8 hours to get through, but I managed to get it to work perfectly and it is pretty awesome!

Added in ec024c6652ce624374b73794901cba0144b1860a

**Comment by TheRooster13** [comment]
That's awesome! Sorry it didn't work correctly. :) I'll try it out tomorrow!
