### ISSUE TITLE
Leaves are non persistent

### ISSUE THREAD

**Issue by mjlee2003** [rebane2001/mapartcraft#57]
the leaves, at least in 1.15.2, aren't persistent, so they break and it ruins the art.

also can you make a feature of changing the file export size above 1x1, sometimes I make very large art and none of the programs I need to export or to convert it to a schematic will work.

**Comment by rebane2001** [comment]
I just tested it in both 1.12.2 and 1.15.2, leaves do not decay if YOU place them manually.
