### ISSUE TITLE
Add minimal required amount of blocks

### ISSUE THREAD

**Issue by MaksymilianP** [rebane2001/mapartcraft#59]
(in map arts bigger than 1x1) the current "Materials" option gives you the amount of materials needed if you'd make all these maps next to each other at the same time, for most map art makers I know, it's simply false, we use the same place for each part and then collect them all into an image. So the "Materials" option could have a counteroption or suboption of "Minimal Required" which would be calculated by comparing each of the material numbers on every map part and choosing the biggest, so you have only the amount you truly need of certain material to complete it, same goes for every material. 

For example if in 1x2 map art you need 1000 gold blocks on the left and 500 gold blocks on the right, you don't need 1500, just 1000 and then reuse some of them on the right part.

For such items that are harder to get that feature would be a really neat option, especially for bigger map arts

**Comment by rebane2001** [comment]
> for most map art makers I know, it's simply false

This is not the case for most map makers I know and it's a hassle to add, so I won't be adding it for now. PRs are welcome however!

**Comment by crubleigh** [comment]
I'd reckon most map makers you know are probably in 1.12. For everyone post-1.14, locking maps and recycling materials is almost the standard. I'm going through closed issues and realized this is exactly the same as a suggestion I put in a bit ago but it'd be a great feature for us map makers playing modern versions of the game.

**Comment by rebane2001** [comment]
Hmm I will consider this

**Comment by rebane2001** [comment]
Added in 7f468ec6402251fdcf8b07f0c4fdcc039ec5fb9e
