### ISSUE TITLE
Gravel

### ISSUE THREAD

**Issue by AlmazikMinecraft** [rebane2001/mapartcraft#61]
As I know from minecraft wiki gravel has similar color to sand in maps. Sometimes you don't have any birches or deserts near you, but you can find gravel underground, so adding it will help some guys making a mapart in survival. Please add it.

**Comment by rebane2001** [comment]
Gravel has a completely different color compared to sand, but I will probably add it regardless

**Comment by rebane2001** [comment]
Added in c1de7198577c5c2d22b5476d1d76c3b43f96c58b
