### ISSUE TITLE
Feature- Add a grid like view for map bigger than 1x1.

### ISSUE THREAD

**Issue by BangCryDie** [rebane2001/mapartcraft#66]
Add a grid-like view for maps bigger than 1x1 so we can see which part of the map contains what image. 
https://imgur.com/a/G3EI4NC  - here's an example

**Comment by rebane2001** [comment]
Interesting, I'll think about it

**Comment by rebane2001** [comment]
Added in 4308c81cec9ef237dda57082933873996e2b25be
