### ISSUE TITLE
Add Greyscale Preset

### ISSUE THREAD

**Issue by Aryezz** [rebane2001/mapartcraft#67]
A preset for greyscale maps would be useful.

The following blocks produce greyscale colours on maps:
* Cobwebs
* Iron Blocks / etc.
* Stone Types
* White, Light Grey, Grey and Black Wool

Other blocks like Cyan Terracotta and Clay produce *almost* grey results, but shouldn't be included in my opinion.

**Comment by rebane2001** [comment]
Added in 1ef8b008809aa1edd82276569cd41d08de5d98fa
