### ISSUE TITLE
Add Iron Bars

### ISSUE THREAD

**Issue by Aryezz** [rebane2001/mapartcraft#68]
Iron bars are the cheapest block that produces the "metal grey colour" (the one that currently only has iron blocks, heavy weighted pressure plates and iron trapdoors), and should therefor be included as an option.

Note that iron bars need a supporting block.

**Comment by rebane2001** [comment]
Confirmed and accepted, will be adding at some point

**Comment by rebane2001** [comment]
Added in 62a8e923ad124e19b5ccd847aa22d22dd14c3f14
