### ISSUE TITLE
Add a table for the heights for the blocks

### ISSUE THREAD

**Issue by RoosterNetyx** [rebane2001/mapartcraft#70]
When enabling staircasing, a 128x128 table with the heights of all the blocks would be really helpful for building especially in survival

**Comment by rebane2001** [comment]
View online lets you do that, but I suppose I could try overlaying the numbers on top

**Comment by RoosterNetyx** [comment]
That would be very helpful thanks! :)

**Comment by rebane2001** [comment]
Added in f3a7811faa021d0dd616ebaf98da51b82c5c216d
