### ISSUE TITLE
1.15.0 mapart schematic size issue on litematica

### ISSUE THREAD

**Issue by mikoethechang** [rebane2001/mapartcraft#72]
I found that the originally north/south dimension of a rotated schematic exceeded map boundaries by one block. I used no dithering, optimized staircasing, and included all blocks but selected planks over logs wherever possible. The image I uploaded was 384x128 in png format. I rotated the schematic so that the three map schematic would run long on the north-south axes, and found that the schematic was 1 block too wide in the east west. I am not a seasoned builder or schematic user, so I am hoping others can attempt to reproduce this. I used maps and show chunk borders to place blocks in order to align the schematic after I switched to the litematica client, and found that the alignment blocks have been exceeded. I am playing on fabric 1.15.2 using litematica 1.15.2, and I selected 1.15.0 for the schematic download version as instructed by the dialogue warning. 

These images are an attempt to show the schematic size and placement vs my marker blocks and chunk grid:

![2020-06-19_17 43 21](https://user-images.githubusercontent.com/6667832/85187602-9598ba00-b255-11ea-9290-57709bbdea88.png)
![2020-06-19_17 44 52](https://user-images.githubusercontent.com/6667832/85187603-97627d80-b255-11ea-91f2-4e90c3cd364a.png)
![2020-06-19_17 45 43](https://user-images.githubusercontent.com/6667832/85187607-9c273180-b255-11ea-99b0-6b265a018fa8.png)
![2020-06-19_17 46 39](https://user-images.githubusercontent.com/6667832/85187609-9e898b80-b255-11ea-9e1c-5acd63821467.png)
![2020-06-19_17 47 27](https://user-images.githubusercontent.com/6667832/85187610-a0ebe580-b255-11ea-8844-249cfc8d6e47.png)
![2020-06-19_17 42 09](https://user-images.githubusercontent.com/6667832/85187615-a6493000-b255-11ea-93d6-4a1f3c771559.png)
![2020-06-19_17 42 33](https://user-images.githubusercontent.com/6667832/85187621-a9dcb700-b255-11ea-87f2-2ab12c79e99a.png)
![2020-06-19_17 43 02](https://user-images.githubusercontent.com/6667832/85187623-ac3f1100-b255-11ea-943c-ad68c81d9a34.png)

These images show the way I tried to confirm that the map edges are lined up with the chunk grid and my marker blocks, which were intended to be just outside the map boundaries:

![2020-06-19_17 50 37](https://user-images.githubusercontent.com/6667832/85187651-d55fa180-b255-11ea-9cee-d595752ff32b.png)
![2020-06-19_17 50 12](https://user-images.githubusercontent.com/6667832/85187652-d85a9200-b255-11ea-81f4-55d2f3a7c843.png)

Thank you for taking the time to read this. I hope the information is useful. Please give me feedback if any of this is not ideal, I am a bit inexperienced in using github except for copy/paste downloading.

**Comment by rebane2001** [comment]
Hey, this is to prevent what's called a "noobline". You must let the map extrude 1 block extra to the north, outside of the boundaries or you will get an ugly line on your topmost pixels.

Additionally, never rotate the schematic. If you wish to rotate the image, do so in an image editor *before* converting it to a schematic.

I'm going to leave this issue open for now until I figure out a better way to explain the concept of a noobline to new users, I hope this helps!

**Comment by rebane2001** [comment]
Noobline info added in 2c9471d7de02ae61b63bfd2c7d1d9b14a163e038
