### ISSUE TITLE
Having issues getting the DAT files to work on my 1.15.2 server since MapArtCraft site update.

### ISSUE THREAD

**Issue by DomPrice** [rebane2001/mapartcraft#73]
Having issues getting the DAT files to work on my 1.15.2 server. 

Using this creator:

https://rebane2001.com/mapartcraft/

The files the website gave me worked fine until the website updates recently. Now no DAT file I export from the website interface will work. In game, when I do a give /give filled_map[map:XX] where XX is the imported DAT file, it gives me a blank map with the next avail ID instead, which I guess means the imported DAT file isn't formatted correctly. 

Tried another image->dat exporter and it imported and worked fine, which leads me to believe there is a problem with the DAT exporter on the site.

**Comment by rebane2001** [comment]
It sounds like you have not made the map IDs before adding the map.dat files - you'll need to create those first
If the issue persists, please upload the broken map.dat file and the working map.dat file in this thread

**Comment by DomPrice** [comment]
Map IDs were present. Blank ID files were already present in the data directory.  

I have included the working, non-working, and original PNG files.

[map-artwork-test.zip](https://github.com/rebane2001/mapartcraft/files/4814646/map-artwork-test.zip)

**Comment by rebane2001** [comment]
Thanks, I'll take a look

**Comment by rebane2001** [comment]
Seems like the issue doesn't affect 1.12, which is the version I do most of my testing on. I have figured out the bug and will be implementing the 1.13+ bugfix soon!

**Comment by rebane2001** [comment]
Fixed in b0b3473c588c6b652c27b7b0814b49dc207962fe

**Comment by DomPrice** [comment]
Thanks! I just tried it and it seems to work for me!
