### ISSUE TITLE
Add Sliders for Image Preprocessing

### ISSUE THREAD

**Issue by Aryezz** [rebane2001/mapartcraft#76]
It would be very useful to have some options for basic image preprocessing, so you wouldnt have to make these changes locally and upload the same image multiple times with different settings.

[Pixatool](https://kronbits.itch.io/pixatool) implements these preprocessing options, see the gif on the linked page or [this Youtube Playlist](https://www.youtube.com/playlist?list=PLLhVKO3HeaaziOkGpVEFWpE5ocNmMa8SJ) for an example of its usage.

Some Options that i would find most useful:
- Saturation
- Contrast
- Brightness

**Comment by rebane2001** [comment]
Perhaps this could be done for a future "advanced mode". I'd definitely add levels to the options

**Comment by rebane2001** [comment]
Added in ebc7e5a6458ebb4308deab44a52d4fd7616bb33f
