### ISSUE TITLE
1.16 slabs

### ISSUE THREAD

**Issue by crubleigh** [rebane2001/mapartcraft#77]
This is an addition to my previous slab request, we need crimson plank slabs and warped plank slabs. The other slabs we need for sure are prismarine brick slabs and regular stone slabs.

**Comment by 0rianel** [comment]
Yes yes please add more slab options I was coming here to ask the same thing! It's so awkward having slabs of every wood but the 1.16 woods in my schematics

**Comment by rebane2001** [comment]
They were already added almost a month ago, a53f9ed7c68b74dd478a034c7a23a55d7e7b6e88
