### ISSUE TITLE
Downloaded Maps not working again in 1.15.2

### ISSUE THREAD

**Issue by DomPrice** [rebane2001/mapartcraft#78]
I think when you updated it to 1.16 it overrode the fix you implemented to my previous issue. Selecting the filled map gives me a new blank map instead of the downloaded map that I loaded onto my server. I attached the files rendered from mapartcraft and the maps I used to generate them. 

Also it will not do more than 10 map images it appears.

![METRA-map-01](https://user-images.githubusercontent.com/857194/86496318-e8d93500-bd4a-11ea-8856-7433bc1c2be0.png)
![METRA-map-02](https://user-images.githubusercontent.com/857194/86496320-e971cb80-bd4a-11ea-9168-3fbedc758c00.png)

[map_100.zip](https://github.com/rebane2001/mapartcraft/files/4871367/map_100.zip)

**Comment by rebane2001** [comment]
Works for me on 1.15.2. Try pressing ctrl+shift+r on the website, maybe that fixes something.
![javaw_2020-07-03_23-49-38](https://user-images.githubusercontent.com/6316541/86496890-ecd77800-bd87-11ea-8c86-93bc1dcab207.png)

As for not being able to download more than 10 files at once, that's a limitation in Chrome and I've written a mitigation in 587ca850069aa9e30261b827c856840ea7bbbbbf, which should let you download more than 10 maps at once from now on

**Comment by DomPrice** [comment]
Works! Thanks for looking into it
