### ISSUE TITLE
(Edit Nvm I got it working) I CAN'T EXPORT NBT FILE ON MCEDIT! I WANT SCHEMATIC!

### ISSUE THREAD

**Issue by Mike0004895** [rebane2001/mapartcraft#94]
NVM got it working! You should add an MCEdit tutorial. Btw, I used mcedit 2.0 so that's why it didn't work.

**Comment by rebane2001** [comment]
This is mentioned in the FAQ. Also, .schematic is an old format that shouldn't be used anymore, I will not be adding support for it.
