### ISSUE TITLE
1.16.2 not working

### ISSUE THREAD

**Issue by elaineandsparky** [rebane2001/mapartcraft#99]
Been using your website for serveral months. Just finished off a project in 1.16.1 and just tried doing a new project in 1.16.2 and I can't get the schematic overlay to load properly. (all mods needed to run this are updated to 1.16.2)
![image](https://user-images.githubusercontent.com/69724087/91654744-72835580-eaa3-11ea-9d78-6ba0088faca7.png)

![image](https://user-images.githubusercontent.com/69724087/91654780-b8d8b480-eaa3-11ea-9a00-a309eb072356.png)

**Comment by rebane2001** [comment]
Are you running the LATEST version of Litematica?

**Comment by elaineandsparky** [comment]
ok now i feel stupid lol all working, thanks for your help :)
